name: Lint, Type Check, and Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Lint with ruff
      run: |
        ruff check pyslingshot/

    - name: Format check with ruff
      run: |
        ruff format --check pyslingshot/

    - name: Type check with mypy
      run: |
        mypy pyslingshot/

    - name: Run tests with pytest
      run: |
        pytest tests/ -v --cov=pyslingshot --cov-report=term-missing
